# Generated by Django 5.1 on 2024-10-10 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_remove_registration_payment_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teammember",
            name="non_technical_events",
        ),
        migrations.RemoveField(
            model_name="teammember",
            name="technical_events",
        ),
    ]
